<?php

use App\Admin\Orders\ColumnFormatter;

return [
    [
        'id' => 'id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.id',
        'search_field' => 'orders.id',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'status',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.status',
        'search_field' => null,
        'format' => new ColumnFormatter('status'),
        'is_default' => true,
    ],
    [
        'id' => 'user_id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.user_id',
        'search_field' => 'orders.user_id',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'name',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.name',
        'search_field' => 'orders.name',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'phone',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => 'orders.phone',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'email',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.email',
        'search_field' => 'orders.email',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'language_id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.language_id',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'delivery_method',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.delivery_method',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'payment_method',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.payment_method',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'payment_status',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.payment_status',
        'search_field' => null,
        'format' => new ColumnFormatter('paymentStatus'),
        'is_default' => true,
    ],
    [
        'id' => 'delivery_address',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.delivery_address',
        'search_field' => 'orders.delivery_address',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'shop_name',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'shops.name->' . app()->getLocale(),
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'currency_id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.currency_id',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'items_cost',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.items_cost',
        'search_field' => null,
        'format' => new ColumnFormatter('sumFormatted'),
        'is_default' => false,
    ],
    [
        'id' => 'shipping_cost',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.shipping_cost',
        'search_field' => null,
        'format' => new ColumnFormatter('sumFormatted'),
        'is_default' => false,
    ],
    [
        'id' => 'total_cost',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.total_cost',
        'search_field' => null,
        'format' => new ColumnFormatter('sumFormatted'),
        'is_default' => true,
    ],
    [
        'id' => 'paid_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.paid_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'completed_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.completed_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'created_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.created_at',
        'search_field' => null,
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'updated_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'orders.updated_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
];
