services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=${APP_URL}
    ports:
      - "8001:80"
    depends_on:
      - app
    networks:
      - nw1

  app:
    build:
      args:
        user: ${DOCKER_APP_USER}
        uid: ${DOCKER_APP_UID}
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - nw1

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - nw1

  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
    networks:
      - nw1

networks:
  nw1:
    name: ${DOCKER_PROXY_NETWORK}
    external: true