<?php

use App\Admin\Users\UserColumnFormatter;

return [
    [
        'id' => 'id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.id',
        'search_field' => 'users.id',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'name',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.name',
        'search_field' => 'users.name',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'email',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.email',
        'search_field' => 'users.email',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'email_verified_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.email_verified_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'phone',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => 'users.phone',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'address',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => 'users.address',
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'role',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => null,
        'format' => new UserColumnFormatter('role'),
        'is_default' => true,
    ],
    [
        'id' => 'is_active',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => null,
        'format' => new UserColumnFormatter('banned'),
        'is_default' => true,
    ],
    [
        'id' => 'created_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.created_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'updated_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'users.updated_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
];
