<?php

use App\Admin\Reviews\ColumnFormatter;

return [
    [
        'id' => 'id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'reviews.id',
        'search_field' => 'reviews.id',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'sku_id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'reviews.sku_id',
        'search_field' => 'reviews.sku_id',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'user_id',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => 'reviews.user_id',
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'term',
        'show_name' => true,
        'class_list' => null,
        'order_by' => null,
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
    [
        'id' => 'mark',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'reviews.mark',
        'search_field' => null,
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'pros',
        'show_name' => true,
        'class_list' => 'text-start',
        'order_by' => null,
        'search_field' => 'reviews.pros',
        'format' => new ColumnFormatter('clipText'),
        'is_default' => true,
    ],
    [
        'id' => 'cons',
        'show_name' => true,
        'class_list' => 'text-start',
        'order_by' => null,
        'search_field' => 'reviews.cons',
        'format' => new ColumnFormatter('clipText'),
        'is_default' => true,
    ],
    [
        'id' => 'comnt',
        'show_name' => true,
        'class_list' => 'text-start',
        'order_by' => null,
        'search_field' => 'reviews.comnt',
        'format' => new ColumnFormatter('clipText'),
        'is_default' => true,
    ],
    [
        'id' => 'created_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'reviews.created_at',
        'search_field' => null,
        'format' => null,
        'is_default' => true,
    ],
    [
        'id' => 'updated_at',
        'show_name' => true,
        'class_list' => null,
        'order_by' => 'reviews.updated_at',
        'search_field' => null,
        'format' => null,
        'is_default' => false,
    ],
];
