name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            eval `ssh-agent -s`
            ssh-add ~/.ssh/eshop2-github
            cd /var/www/eshop2
            git pull origin master
            docker compose -f compose.prod.yml exec eshop2-app php artisan down
            docker compose -f compose.prod.yml exec eshop2-app composer install --no-interaction --optimize-autoloader --no-dev
            docker compose -f compose.prod.yml exec eshop2-app php artisan migrate --force
            docker compose -f compose.prod.yml exec eshop2-app php artisan cache:clear
            docker compose -f compose.prod.yml exec eshop2-app php artisan up
